plugins {
    id 'com.android.application'
}

android {
    namespace 'com.whisper.wowaudio'
    compileSdk 36

    defaultConfig {
        applicationId 'com.whisper.wowaudio'
        minSdk 23
        targetSdk 36
        versionCode 4
        versionName '1.0.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
}
